# Generated by Django 5.2.1 on 2025-05-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_clients', '0001_initial'),
        ('app_coordinators', '0001_initial'),
        ('app_services', '0002_alter_service_price'),
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True, verbose_name='Reservation Date')),
                ('service_date', models.DateTimeField(verbose_name='Service Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_clients.clients', verbose_name='Client')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_coordinator', to='app_coordinators.coordinator', verbose_name='Coordinator')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_as_employee', to='employees_app.employee', verbose_name='Employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['service_date'],
            },
        ),
    ]
