# Generated by Django 5.2.1 on 2025-05-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employees_app.employee')),
                ('document_number', models.IntegerField(unique=True)),
                ('discharge_date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('employees_app.employee',),
        ),
    ]
